### PR TITLE
Fix permissions

### PR DESCRIPTION
**Pull request by kambysese**
@ilogue read permission issue resolved. Somehow I get the impression this PR is not going to work though in terms of merging.

### CODE REVIEW

**Comment by ilogue** [comment]
This  PR also contains the changes in the other one. I'm guessing you branched this one off the `mnefun-firstgo` branch

**Comment by kambysese** [comment]
Afraid so, lets abandon this and I'll branch of master and redo PR.

**Comment by ilogue** [comment]
Or just leave it and we'll merge after the other one

**Comment by kambysese** [comment]
Oh exciting, a merge! :disappointed:

**Pull request merged**
