### PR TITLE
Redo fix

### PR DESCRIPTION
**Pull request by kambysese**
@ilogue this needs to be merged in place of previous PR using `.tolist()` that causes an `AttributeError`.

### CODE REVIEW

**Comment by kambysese** [comment]
God I hate this shit :angry: how is there still conflicts after rebasing?

**Comment by ilogue** [comment]
I don't understand rebasing myself. There is a conflict because we both changed a version of `mnefunsupport.py`. Just add my change (moving the customprov line inside the loop) and mark as resolved, then commit.

**Comment by ilogue** [comment]
Looks like you merged `redo-fix` but you want to merge `master`, I think?

**Comment by kambysese** [comment]
I want to merge `upstream/master` which is what I thought rebase onto does...

**Comment by kambysese** [comment]
And when I try to merge now it says everything is up to date....ugh every time I PR 2 deletions it takes 34 commits to make it work

**Pull request closed without merging**
